"""Create restaurants, pizzas, restaurant_pizzas tables

Revision ID: 70e802b7d3a5
Revises: 589b2ca2cb59
Create Date: 2024-01-21 13:36:26.278798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e802b7d3a5'
down_revision = '589b2ca2cb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('pizza_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('restaurant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'pizzas', ['pizza_id'], ['id'])
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('restaurant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('pizza_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
